### ISSUE TITLE
More ergonomic usage

### ISSUE THREAD

**Issue by ramonGonzEdu** [devon2018/snippet#27]
This is from a Reddit post I made, but I believe it works as a suggestion

You can select code in a file then drag it in (or a command palette command) and you can set tags (language is added automatically based on file). Then you can drag and drop the saved snippets into your code or the default click to insert behavior. There should be a search bar to search snippets, and maybe snippets are only shown if they have a matching language tag to the currently open file.

**Comment by devon2018** [comment]
Hi @ramonGonzEdu 

I am working on adding search to the sidebar in a later release. at the moment this can be done by using the commands `cmd + shift + i`  which will allow you to search snippets and add them to your content.


at the moment drag and drop is not supported by Vscode extensions, but theres a feature request with them for this so I will look into that when it becomes available. 

limiting snippets to the current filetype wouldn't work because in some situations you would want it available, for example if you had an html snippet and wanted to use that in a React or VueJs component you should be able to.
